import type { Board, Component } from './types.ts';
export const catalogDate = '2026-09-05';
export const boards: Board[] = [
  {
    id: 'esp32-devkitc-v4',
    name: 'ESP32-DevKitC V4',
    family: 'Espressif',
    mcu: 'ESP32-WROOM-32E',
    logicVoltage: 3.3,
    analogInputs: 16,
    digitalPins: 26,
    description:
      'Espressif development board with Wi-Fi and Bluetooth. V4 profile with the WROOM-32E module.',
    sourceUrl:
      'https://docs.espressif.com/projects/esp-dev-kits/en/latest/esp32/esp32-devkitc/user_guide.html',
    notes: [
      'This profile is for WROOM-32E; GPIO16/17 availability differs on WROVER versions.',
      'Flash, boot-strapping, and UART0 pins are excluded from automatic assignment. GPIO34/35/36/39 are ADC-input-only in this profile and have no internal pull-ups.',
      'ADC1 pins are used. GPIO and ADC inputs are not 5 V tolerant.',
    ],
    profile: {
      digital: ['GPIO4', 'GPIO16', 'GPIO17', 'GPIO18', 'GPIO19', 'GPIO23'],
      analog: ['GPIO34', 'GPIO35', 'GPIO36', 'GPIO39'],
      pwm: ['GPIO25', 'GPIO26', 'GPIO27', 'GPIO32', 'GPIO33'],
      i2c: { sda: 'GPIO21', scl: 'GPIO22' },
      fqbn: 'esp32:esp32:esp32',
      adc: 'esp32',
      adcReference: 3.3,
      i2cSetup: 'esp32',
      codePins: Object.fromEntries(
        [4, 16, 17, 18, 19, 21, 22, 23, 25, 26, 27, 32, 33, 34, 35, 36, 39].map(
          (p) => ['GPIO' + p, String(p)],
        ),
      ),
    },
  },
  {
    id: 'raspberry-pi-pico',
    name: 'Raspberry Pi Pico',
    family: 'Raspberry Pi',
    mcu: 'RP2040 · dual Cortex-M0+',
    logicVoltage: 3.3,
    analogInputs: 3,
    digitalPins: 26,
    description:
      'Original Pico with PIO and a dual-core RP2040. C++ code generation uses the Arduino-Pico core.',
    sourceUrl:
      'https://www.raspberrypi.com/documentation/microcontrollers/pico-series.html',
    notes: [
      'The original Pico is the non-wireless RP2040 version.',
      'GP26–28 are ADC inputs. GP0/1 are reserved for serial communication; I²C0 is explicitly configured on GP4/5.',
      'GPIO inputs use 3.3 V logic. Arduino-Pico core: Earle Philhower rp2040:rp2040:rpipico.',
    ],
    profile: {
      digital: [
        'GP2',
        'GP3',
        'GP6',
        'GP7',
        'GP8',
        'GP9',
        'GP10',
        'GP11',
        'GP12',
        'GP13',
      ],
      analog: ['GP26', 'GP27', 'GP28'],
      pwm: [
        'GP14',
        'GP15',
        'GP16',
        'GP17',
        'GP18',
        'GP19',
        'GP20',
        'GP21',
        'GP22',
      ],
      i2c: { sda: 'GP4', scl: 'GP5' },
      fqbn: 'rp2040:rp2040:rpipico',
      adc: 'set10',
      adcReference: 3.3,
      i2cSetup: 'rp2040',
      codePins: Object.fromEntries(
        Array.from({ length: 29 }, (_, p) => ['GP' + p, String(p)]),
      ),
    },
  },
  {
    id: 'uno-rev3',
    name: 'Arduino UNO R3',
    family: 'UNO',
    mcu: 'ATmega328P',
    logicVoltage: 5,
    analogInputs: 6,
    digitalPins: 14,
    description:
      'Classic AVR development board for basic I/O and sensor examples.',
    sourceUrl: 'https://docs.arduino.cc/hardware/uno-rev3/',
    notes: [
      'codeProfile: researched using official pin documentation; inclusion in this catalog alone does not imply compilation or hardware testing.',
      'Default digital pins are a project-specific selection from documented GPIO. Connected peripherals and timer/pin conflicts require separate checks.',
    ],
    profile: {
      digital: ['D2', 'D4', 'D7', 'D8'],
      analog: ['A0', 'A1', 'A2', 'A3', 'A4', 'A5'],
      pwm: ['D3', 'D5', 'D6', 'D9', 'D10', 'D11'],
      i2c: {
        sda: 'A4',
        scl: 'A5',
      },
      fqbn: 'arduino:avr:uno',
      adc: 'avr10',
      adcReference: 5,
    },
  },
  {
    id: 'uno-rev3-smd',
    name: 'Arduino UNO R3 SMD',
    family: 'UNO',
    mcu: 'ATmega328P',
    logicVoltage: 5,
    analogInputs: 6,
    digitalPins: 14,
    description: 'The same core MCU as UNO R3, soldered directly to the board.',
    sourceUrl: 'https://docs.arduino.cc/hardware/uno-rev3-smd/',
    notes: [],
  },
  {
    id: 'uno-mini-limited-edition',
    name: 'Arduino UNO Mini Limited Edition',
    family: 'UNO',
    mcu: 'ATmega328P',
    logicVoltage: null,
    analogInputs: null,
    digitalPins: null,
    description:
      'A compact special-edition UNO with USB-C and different pin spacing.',
    sourceUrl: 'https://docs.arduino.cc/hardware/uno-mini-limited-edition/',
    notes: [],
  },
  {
    id: 'uno-r4-minima',
    name: 'Arduino UNO R4 Minima',
    family: 'UNO',
    mcu: 'Renesas RA4M1',
    logicVoltage: 5,
    analogInputs: 6,
    digitalPins: 14,
    description: '32-bit UNO with 5 V header pins, an enhanced ADC, and a DAC.',
    sourceUrl: 'https://docs.arduino.cc/hardware/uno-r4-minima/',
    notes: [
      'codeProfile: researched using official pin documentation; inclusion in this catalog alone does not imply compilation or hardware testing.',
      'Default digital pins are a project-specific selection from documented GPIO. Connected peripherals and timer/pin conflicts require separate checks.',
      'D4/D5 are shared with CAN and must be reserved when CAN is used. Header GPIO voltage is 5 V; the VIN supply range is not the logic voltage.',
    ],
    profile: {
      digital: ['D2', 'D7', 'D8'],
      analog: ['A0', 'A1', 'A2', 'A3', 'A4', 'A5'],
      pwm: ['D3', 'D5', 'D6', 'D9', 'D10', 'D11'],
      i2c: {
        sda: 'A4',
        scl: 'A5',
      },
      fqbn: 'arduino:renesas_uno:minima',
      adc: 'set10',
      adcReference: 5,
    },
  },
  {
    id: 'uno-r4-wifi',
    name: 'Arduino UNO R4 WiFi',
    family: 'UNO',
    mcu: 'Renesas RA4M1; ESP32-S3 connectivity processor',
    logicVoltage: 5,
    analogInputs: 6,
    digitalPins: 14,
    description:
      'RA4M1-based UNO with wireless connectivity and an LED matrix.',
    sourceUrl: 'https://docs.arduino.cc/hardware/uno-r4-wifi/',
    notes: [
      'codeProfile: researched using official pin documentation; inclusion in this catalog alone does not imply compilation or hardware testing.',
      'Default digital pins are a project-specific selection from documented GPIO. Connected peripherals and timer/pin conflicts require separate checks.',
      'The main A4/A5 Wire bus header is 5 V; the separate Qwiic connector uses the 3.3 V Wire1 bus. ESP32-S3 is not the default sketch MCU.',
    ],
    profile: {
      digital: ['D2', 'D4', 'D7', 'D8'],
      analog: ['A0', 'A1', 'A2', 'A3', 'A4', 'A5'],
      pwm: ['D3', 'D5', 'D6', 'D9', 'D10', 'D11'],
      i2c: {
        sda: 'A4',
        scl: 'A5',
      },
      fqbn: 'arduino:renesas_uno:unor4wifi',
      adc: 'set10',
      adcReference: 5,
    },
  },
  {
    id: 'uno-wifi-rev2',
    name: 'Arduino UNO WiFi Rev2',
    family: 'UNO',
    mcu: 'ATmega4809',
    logicVoltage: null,
    analogInputs: null,
    digitalPins: null,
    description:
      'AVR UNO with a Wi-Fi/Bluetooth module; its MCU differs from the classic R3.',
    sourceUrl: 'https://docs.arduino.cc/hardware/uno-wifi-rev2/',
    notes: [],
  },
  {
    id: 'uno-q',
    name: 'Arduino UNO Q',
    family: 'UNO',
    mcu: 'STM32U585 MCU; Qualcomm Dragonwing QRB2210 MPU',
    logicVoltage: null,
    analogInputs: null,
    digitalPins: null,
    description:
      'A board combining Linux applications with real-time MCU firmware.',
    sourceUrl: 'https://docs.arduino.cc/hardware/uno-q/',
    notes: [],
  },
  {
    id: 'nano',
    name: 'Arduino Nano (classic)',
    family: 'Nano',
    mcu: 'ATmega328P',
    logicVoltage: 5,
    analogInputs: 8,
    digitalPins: 14,
    description: 'Classic compact AVR board; A6/A7 are analog-input-only.',
    sourceUrl: 'https://docs.arduino.cc/hardware/nano/',
    notes: [
      'codeProfile: researched using official pin documentation; inclusion in this catalog alone does not imply compilation or hardware testing.',
      'Default digital pins are a project-specific selection from documented GPIO. Connected peripherals and timer/pin conflicts require separate checks.',
      'A6 and A7 are not digital GPIO/PWM pins; use them as analog inputs.',
      'A Nano with an old bootloader may require cpu=atmega328old. This profile does not cover clones or ATmega168 variants.',
    ],
    profile: {
      digital: ['D2', 'D4', 'D7', 'D8'],
      analog: ['A0', 'A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7'],
      pwm: ['D3', 'D5', 'D6', 'D9', 'D10', 'D11'],
      i2c: {
        sda: 'A4',
        scl: 'A5',
      },
      fqbn: 'arduino:avr:nano:cpu=atmega328',
      adc: 'avr10',
      adcReference: 5,
    },
  },
  {
    id: 'nano-every',
    name: 'Arduino Nano Every',
    family: 'Nano',
    mcu: 'ATmega4809',
    logicVoltage: 5,
    analogInputs: 8,
    digitalPins: 14,
    description:
      'A newer AVR in the Nano form factor, with five supported PWM outputs.',
    sourceUrl: 'https://docs.arduino.cc/hardware/nano-every/',
    notes: [
      'codeProfile: researched using official pin documentation; inclusion in this catalog alone does not imply compilation or hardware testing.',
      'Default digital pins are a project-specific selection from documented GPIO. Connected peripherals and timer/pin conflicts require separate checks.',
      'D11 is not assigned as PWM on Nano Every; there is no DAC. The official store specification is more consistent than the DAC0 label in some datasheet copies.',
    ],
    profile: {
      digital: ['D2', 'D4', 'D7', 'D8'],
      analog: ['A0', 'A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7'],
      pwm: ['D3', 'D5', 'D6', 'D9', 'D10'],
      i2c: {
        sda: 'A4',
        scl: 'A5',
      },
      fqbn: 'arduino:megaavr:nona4809',
      adc: 'avr10',
      adcReference: 5,
    },
  },
  {
    id: 'nano-esp32',
    name: 'Arduino Nano ESP32',
    family: 'Nano',
    mcu: 'ESP32-S3 (u-blox NORA-W106)',
    logicVoltage: 3.3,
    analogInputs: 8,
    digitalPins: 14,
    description:
      '3.3 V Nano with Wi-Fi/Bluetooth and configurable pin numbering.',
    sourceUrl: 'https://docs.arduino.cc/hardware/nano-esp32/',
    notes: [
      'codeProfile: researched using official pin documentation; inclusion in this catalog alone does not imply compilation or hardware testing.',
      'Default digital pins are a project-specific selection from documented GPIO. Connected peripherals and timer/pin conflicts require separate checks.',
      'Use symbols such as D2; pin numbering can change in the IDE menu. The physical D2 label corresponds to GPIO5.',
      'The PWM list follows the tilde marks on page 1 of the official full pinout. It does not imply simultaneous independent PWM channels on every pin.',
      'Analog inputs tolerate 3.3 V; evaluate the ADC measurement range, calibration, and attenuation settings separately.',
    ],
    profile: {
      digital: ['D2', 'D4', 'D7', 'D8'],
      analog: ['A0', 'A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7'],
      pwm: [
        'D0',
        'D1',
        'D2',
        'D3',
        'D4',
        'D5',
        'D6',
        'D7',
        'D8',
        'D9',
        'D10',
        'D11',
        'D12',
        'D13',
        'A0',
        'A1',
        'A2',
        'A3',
        'A4',
        'A5',
        'A6',
        'A7',
      ],
      i2c: {
        sda: 'A4',
        scl: 'A5',
      },
      fqbn: 'arduino:esp32:nano_nora',
      adc: 'esp32',
      adcReference: 3.3,
    },
  },
  {
    id: 'nano-33-ble',
    name: 'Arduino Nano 33 BLE',
    family: 'Nano',
    mcu: 'Nordic nRF52840',
    logicVoltage: 3.3,
    analogInputs: 8,
    digitalPins: null,
    description:
      'First-generation BLE board with Bluetooth LE and motion sensing.',
    sourceUrl: 'https://docs.arduino.cc/hardware/nano-33-ble/',
    notes: [],
    lifecycle: 'endOfLife',
  },
  {
    id: 'nano-33-ble-rev2',
    name: 'Arduino Nano 33 BLE Rev2',
    family: 'Nano',
    mcu: 'Nordic nRF52840',
    logicVoltage: null,
    analogInputs: null,
    digitalPins: null,
    description:
      'Updated Nano with Bluetooth LE and a nine-axis motion sensor.',
    sourceUrl: 'https://docs.arduino.cc/hardware/nano-33-ble-rev2/',
    notes: [],
  },
  {
    id: 'nano-33-ble-sense',
    name: 'Arduino Nano 33 BLE Sense',
    family: 'Nano',
    mcu: 'Nordic nRF52840',
    logicVoltage: 3.3,
    analogInputs: null,
    digitalPins: null,
    description:
      'Embedded ML development board with environmental sensors and a microphone.',
    sourceUrl: 'https://docs.arduino.cc/hardware/nano-33-ble-sense/',
    notes: [],
    lifecycle: 'endOfLife',
  },
  {
    id: 'nano-33-ble-sense-rev2',
    name: 'Arduino Nano 33 BLE Sense Rev2',
    family: 'Nano',
    mcu: 'Nordic nRF52840',
    logicVoltage: null,
    analogInputs: null,
    digitalPins: null,
    description:
      'Nano for embedded machine learning with an updated sensor suite.',
    sourceUrl: 'https://docs.arduino.cc/hardware/nano-33-ble-sense-rev2/',
    notes: [],
  },
  {
    id: 'nano-33-iot',
    name: 'Arduino Nano 33 IoT',
    family: 'Nano',
    mcu: 'Microchip SAMD21',
    logicVoltage: 3.3,
    analogInputs: 8,
    digitalPins: null,
    description: 'IoT-focused Nano with Wi-Fi/Bluetooth and an IMU.',
    sourceUrl: 'https://docs.arduino.cc/hardware/nano-33-iot/',
    notes: [],
  },
  {
    id: 'nano-rp2040-connect',
    name: 'Arduino Nano RP2040 Connect',
    family: 'Nano',
    mcu: 'Raspberry Pi RP2040',
    logicVoltage: 3.3,
    analogInputs: null,
    digitalPins: null,
    description: 'Nano with RP2040, a wireless module, and sensors.',
    sourceUrl: 'https://docs.arduino.cc/hardware/nano-rp2040-connect/',
    notes: [],
    lifecycle: 'endOfLife',
  },
  {
    id: 'nano-matter',
    name: 'Arduino Nano Matter',
    family: 'Nano',
    mcu: 'Silicon Labs MGM240S',
    logicVoltage: null,
    analogInputs: null,
    digitalPins: null,
    description: 'Compact wireless board for Matter and Thread projects.',
    sourceUrl: 'https://docs.arduino.cc/hardware/nano-matter/',
    notes: [],
  },
  {
    id: 'nano-r4',
    name: 'Arduino Nano R4',
    family: 'Nano',
    mcu: 'Renesas RA4M1',
    logicVoltage: 5,
    analogInputs: null,
    digitalPins: null,
    description: 'RA4M1 in the Nano form factor, with Qwiic and CAN support.',
    sourceUrl: 'https://docs.arduino.cc/hardware/nano-r4/',
    notes: [
      'GPIO headers are 5 V; Qwiic logic is 3.3 V. Pin and code profiles have not been validated in this catalog.',
    ],
  },
  {
    id: 'mega-2560',
    name: 'Arduino Mega 2560 Rev3',
    family: 'Mega',
    mcu: 'ATmega2560',
    logicVoltage: 5,
    analogInputs: 16,
    digitalPins: 54,
    description:
      'AVR board with a large pin count and four hardware serial ports.',
    sourceUrl: 'https://docs.arduino.cc/hardware/mega-2560/',
    notes: [
      'codeProfile: researched using official pin documentation; inclusion in this catalog alone does not imply compilation or hardware testing.',
      'Default digital pins are a project-specific selection from documented GPIO. Connected peripherals and timer/pin conflicts require separate checks.',
    ],
    profile: {
      digital: ['D22', 'D23', 'D24', 'D25'],
      analog: ['A0', 'A1', 'A2', 'A3', 'A4', 'A5'],
      pwm: [
        'D2',
        'D3',
        'D4',
        'D5',
        'D6',
        'D7',
        'D8',
        'D9',
        'D10',
        'D11',
        'D12',
        'D13',
        'D44',
        'D45',
        'D46',
      ],
      i2c: {
        sda: 'D20',
        scl: 'D21',
      },
      fqbn: 'arduino:avr:mega:cpu=atmega2560',
      adc: 'avr10',
      adcReference: 5,
    },
  },
  {
    id: 'due',
    name: 'Arduino Due',
    family: 'Mega',
    mcu: 'Atmel SAM3X8E',
    logicVoltage: 3.3,
    analogInputs: 12,
    digitalPins: 54,
    description:
      '32-bit Cortex-M3 board with 54 digital pins and 12 analog inputs.',
    sourceUrl: 'https://docs.arduino.cc/hardware/due/',
    notes: [],
  },
  {
    id: 'giga-r1-wifi',
    name: 'Arduino GIGA R1 WiFi',
    family: 'Mega',
    mcu: 'STM32H747XI',
    logicVoltage: 3.3,
    analogInputs: null,
    digitalPins: 76,
    description:
      'Dual cores, camera/display connections, and extensive GPIO capacity.',
    sourceUrl: 'https://docs.arduino.cc/hardware/giga-r1-wifi/',
    notes: [],
  },
  {
    id: 'leonardo',
    name: 'Arduino Leonardo',
    family: 'Classic',
    mcu: 'ATmega32U4',
    logicVoltage: 5,
    analogInputs: 12,
    digitalPins: 20,
    description:
      'Native USB support for keyboard/mouse and general control projects.',
    sourceUrl: 'https://docs.arduino.cc/hardware/leonardo/',
    notes: [
      'codeProfile: researched using official pin documentation; inclusion in this catalog alone does not imply compilation or hardware testing.',
      'Default digital pins are a project-specific selection from documented GPIO. Connected peripherals and timer/pin conflicts require separate checks.',
      'A6,A7,A8,A9,A10,A11 alias D4,D6,D8,D9,D10,D12 respectively. Serial uses USB CDC; Serial1 uses D0/D1.',
    ],
    profile: {
      digital: ['D4', 'D7', 'D8'],
      analog: ['A0', 'A1', 'A2', 'A3', 'A4', 'A5'],
      pwm: ['D3', 'D5', 'D6', 'D9', 'D10', 'D11', 'D13'],
      i2c: {
        sda: 'D2',
        scl: 'D3',
      },
      fqbn: 'arduino:avr:leonardo',
      adc: 'avr10',
      adcReference: 5,
    },
  },
  {
    id: 'micro',
    name: 'Arduino Micro',
    family: 'Classic',
    mcu: 'ATmega32U4',
    logicVoltage: 5,
    analogInputs: 12,
    digitalPins: 20,
    description: 'Leonardo-style native USB features in a compact form factor.',
    sourceUrl: 'https://docs.arduino.cc/hardware/micro/',
    notes: [
      'codeProfile: researched using official pin documentation; inclusion in this catalog alone does not imply compilation or hardware testing.',
      'Default digital pins are a project-specific selection from documented GPIO. Connected peripherals and timer/pin conflicts require separate checks.',
      'A6,A7,A8,A9,A10,A11 alias D4,D6,D8,D9,D10,D12 respectively. Analog/digital aliases are not separate physical pins.',
    ],
    profile: {
      digital: ['D4', 'D7', 'D8'],
      analog: ['A0', 'A1', 'A2', 'A3', 'A4', 'A5'],
      pwm: ['D3', 'D5', 'D6', 'D9', 'D10', 'D11', 'D13'],
      i2c: {
        sda: 'D2',
        scl: 'D3',
      },
      fqbn: 'arduino:avr:micro',
      adc: 'avr10',
      adcReference: 5,
    },
  },
  {
    id: 'zero',
    name: 'Arduino Zero',
    family: 'Classic',
    mcu: 'Microchip SAMD21',
    logicVoltage: 3.3,
    analogInputs: 6,
    digitalPins: 14,
    description: '32-bit Cortex-M0+ with an onboard EDBG debugger.',
    sourceUrl: 'https://docs.arduino.cc/hardware/zero/',
    notes: [
      'codeProfile: researched using official pin documentation; inclusion in this catalog alone does not imply compilation or hardware testing.',
      'Default digital pins are a project-specific selection from documented GPIO. Connected peripherals and timer/pin conflicts require separate checks.',
      'PWM is limited to digital header pins marked with a tilde in the official full pinout; additional timer outputs are outside this profile. A0 is a DAC output with analogWrite.',
      'I2C uses separate SDA/SCL pins; do not use the UNO R3 A4/A5 mapping. Default SPI also differs from the UNO R3 D11–D13 mapping.',
      'The FQBN selects the programming USB port; use arduino:samd:arduino_zero_native for native USB. Serial uses the EDBG port; native USB serial uses SerialUSB.',
    ],
    profile: {
      digital: ['D2', 'D4', 'D7', 'D8'],
      analog: ['A0', 'A1', 'A2', 'A3', 'A4', 'A5'],
      pwm: ['D3', 'D4', 'D5', 'D6', 'D8', 'D9', 'D10', 'D11', 'D12', 'D13'],
      i2c: {
        sda: 'D20',
        scl: 'D21',
      },
      fqbn: 'arduino:samd:arduino_zero_edbg',
      adc: 'set10',
      adcReference: 3.3,
    },
  },
  {
    id: 'yun-rev2',
    name: 'Arduino Yún Rev2',
    family: 'Classic',
    mcu: 'Not verified',
    logicVoltage: null,
    analogInputs: null,
    digitalPins: null,
    description:
      'Legacy networking board combining Linux and Arduino environments.',
    sourceUrl: 'https://docs.arduino.cc/hardware/yun-rev2/',
    notes: [],
    lifecycle: 'endOfLife',
  },
  {
    id: 'mkr-1000-wifi',
    name: 'Arduino MKR 1000 WiFi',
    family: 'MKR',
    mcu: 'Microchip SAMD21',
    logicVoltage: 3.3,
    analogInputs: 7,
    digitalPins: null,
    description: 'One of the first MKR-family boards with Wi-Fi.',
    sourceUrl: 'https://docs.arduino.cc/hardware/mkr-1000-wifi/',
    notes: [],
    lifecycle: 'endOfLife',
  },
  {
    id: 'mkr-wifi-1010',
    name: 'Arduino MKR WiFi 1010',
    family: 'MKR',
    mcu: 'Microchip SAMD21',
    logicVoltage: 3.3,
    analogInputs: 7,
    digitalPins: null,
    description: 'SAMD21 board with Wi-Fi/Bluetooth connectivity.',
    sourceUrl: 'https://docs.arduino.cc/hardware/mkr-wifi-1010/',
    notes: [],
  },
  {
    id: 'mkr-fox-1200',
    name: 'Arduino MKR FOX 1200',
    family: 'MKR',
    mcu: 'Microchip SAMD21',
    logicVoltage: 3.3,
    analogInputs: 7,
    digitalPins: null,
    description: 'Legacy low-power communication board based on Sigfox.',
    sourceUrl: 'https://docs.arduino.cc/hardware/mkr-fox-1200/',
    notes: [],
    lifecycle: 'endOfLife',
  },
  {
    id: 'mkr-gsm-1400',
    name: 'Arduino MKR GSM 1400',
    family: 'MKR',
    mcu: 'Microchip SAMD21',
    logicVoltage: 3.3,
    analogInputs: 7,
    digitalPins: null,
    description: 'Legacy cellular IoT board with a GSM/3G module.',
    sourceUrl: 'https://docs.arduino.cc/hardware/mkr-gsm-1400/',
    notes: [],
    lifecycle: 'endOfLife',
  },
  {
    id: 'mkr-nb-1500',
    name: 'Arduino MKR NB 1500',
    family: 'MKR',
    mcu: 'Microchip SAMD21',
    logicVoltage: 3.3,
    analogInputs: 7,
    digitalPins: null,
    description: 'Cellular IoT board with NB-IoT and LTE-M support.',
    sourceUrl: 'https://docs.arduino.cc/hardware/mkr-nb-1500/',
    notes: [],
  },
  {
    id: 'mkr-wan-1300',
    name: 'Arduino MKR WAN 1300',
    family: 'MKR',
    mcu: 'Microchip SAMD21',
    logicVoltage: 3.3,
    analogInputs: 7,
    digitalPins: null,
    description: "Arduino's first LoRa MKR board.",
    sourceUrl: 'https://docs.arduino.cc/hardware/mkr-wan-1300/',
    notes: [],
  },
  {
    id: 'mkr-wan-1310',
    name: 'Arduino MKR WAN 1310',
    family: 'MKR',
    mcu: 'Microchip SAMD21',
    logicVoltage: 3.3,
    analogInputs: 7,
    digitalPins: null,
    description: 'MKR for LoRa connectivity and low-power applications.',
    sourceUrl: 'https://docs.arduino.cc/hardware/mkr-wan-1310/',
    notes: [],
  },
  {
    id: 'mkr-vidor-4000',
    name: 'Arduino MKR Vidor 4000',
    family: 'MKR',
    mcu: 'Microchip SAMD21',
    logicVoltage: 3.3,
    analogInputs: 7,
    digitalPins: null,
    description: 'Includes an Intel Cyclone 10CL016 FPGA alongside SAMD21.',
    sourceUrl: 'https://docs.arduino.cc/hardware/mkr-vidor-4000/',
    notes: [],
    lifecycle: 'endOfLife',
  },
  {
    id: 'mkr-zero',
    name: 'Arduino MKR Zero',
    family: 'MKR',
    mcu: 'Microchip SAMD21',
    logicVoltage: 3.3,
    analogInputs: 7,
    digitalPins: null,
    description: 'SAMD21 board for SD card and audio projects.',
    sourceUrl: 'https://docs.arduino.cc/hardware/mkr-zero/',
    notes: [],
  },
  {
    id: 'portenta-h7',
    name: 'Arduino Portenta H7',
    family: 'Portenta',
    mcu: 'STM32H747XI',
    logicVoltage: null,
    analogInputs: null,
    digitalPins: null,
    description: 'Dual-core M7/M4 MCU module with high-density connectors.',
    sourceUrl: 'https://docs.arduino.cc/hardware/portenta-h7/',
    notes: [],
  },
  {
    id: 'portenta-h7-lite',
    name: 'Arduino Portenta H7 Lite',
    family: 'Portenta',
    mcu: 'STM32H747XI',
    logicVoltage: null,
    analogInputs: null,
    digitalPins: null,
    description: 'A simplified dual-core module in the Portenta H7 family.',
    sourceUrl: 'https://docs.arduino.cc/hardware/portenta-h7-lite/',
    notes: [],
  },
  {
    id: 'portenta-h7-lite-connected',
    name: 'Arduino Portenta H7 Lite Connected',
    family: 'Portenta',
    mcu: 'STM32H747XI',
    logicVoltage: null,
    analogInputs: null,
    digitalPins: null,
    description: 'H7 Lite module with wireless connectivity.',
    sourceUrl: 'https://docs.arduino.cc/hardware/portenta-h7-lite-connected/',
    notes: [],
  },
  {
    id: 'portenta-c33',
    name: 'Arduino Portenta C33',
    family: 'Portenta',
    mcu: 'Renesas RA6M5 (R7FA6M5BH2CBG)',
    logicVoltage: null,
    analogInputs: null,
    digitalPins: null,
    description: 'Portenta module with Cortex-M33 and wireless connectivity.',
    sourceUrl: 'https://docs.arduino.cc/hardware/portenta-c33/',
    notes: [],
  },
  {
    id: 'portenta-x8',
    name: 'Arduino Portenta X8',
    family: 'Portenta',
    mcu: 'STM32H747XI MCU; NXP i.MX 8M Mini MPU',
    logicVoltage: null,
    analogInputs: null,
    digitalPins: null,
    description: 'Hybrid module for Linux containers and MCU tasks.',
    sourceUrl: 'https://docs.arduino.cc/hardware/portenta-x8/',
    notes: [],
  },
  {
    id: 'nicla-sense-me',
    name: 'Arduino Nicla Sense ME',
    family: 'Nicla',
    mcu: 'Nordic nRF52832',
    logicVoltage: null,
    analogInputs: null,
    digitalPins: null,
    description:
      'Compact data acquisition board with Bosch motion and environmental sensors.',
    sourceUrl: 'https://docs.arduino.cc/hardware/nicla-sense-me/',
    notes: [],
  },
  {
    id: 'nicla-vision',
    name: 'Arduino Nicla Vision',
    family: 'Nicla',
    mcu: 'STM32H747AII6',
    logicVoltage: null,
    analogInputs: null,
    digitalPins: null,
    description:
      'Vision-processing board with a camera, microphone, and motion sensors.',
    sourceUrl: 'https://docs.arduino.cc/hardware/nicla-vision/',
    notes: [],
  },
  {
    id: 'nicla-voice',
    name: 'Arduino Nicla Voice',
    family: 'Nicla',
    mcu: 'Nordic nRF52832; Syntiant NDP120 ML processor',
    logicVoltage: null,
    analogInputs: null,
    digitalPins: null,
    description:
      'Dedicated ML board for low-power speech and motion recognition.',
    sourceUrl: 'https://docs.arduino.cc/hardware/nicla-voice/',
    notes: [
      'logicVoltage is left null because the logic level can depend on the LDO/level-shifter configuration.',
    ],
  },
  {
    id: 'arduino-101',
    name: 'Arduino 101',
    family: 'Legacy',
    mcu: 'Intel Curie',
    logicVoltage: 3.3,
    analogInputs: null,
    digitalPins: null,
    description: 'Discontinued Curie-based board; catalog entry only.',
    sourceUrl: 'https://docs.arduino.cc/retired/boards/arduino-101-619/',
    notes: [],
    lifecycle: 'retired',
  },
  {
    id: 'arduino-duemilanove',
    name: 'Arduino Duemilanove',
    family: 'Legacy',
    mcu: 'ATmega168 / ATmega328P (version-dependent)',
    logicVoltage: null,
    analogInputs: null,
    digitalPins: null,
    description:
      'Legacy AVR development board requiring an explicit MCU variant selection.',
    sourceUrl: 'https://docs.arduino.cc/retired/boards/arduino-duemilanove/',
    notes: [],
    lifecycle: 'retired',
  },
  {
    id: 'arduino-pro-mini',
    name: 'Arduino Pro Mini',
    family: 'Legacy',
    mcu: 'Not verified',
    logicVoltage: null,
    analogInputs: null,
    digitalPins: null,
    description:
      'Legacy compact board with voltage and processor variants; verify the exact version.',
    sourceUrl: 'https://docs.arduino.cc/retired/boards/arduino-pro-mini/',
    notes: [],
    lifecycle: 'retired',
  },
];
export const components: Component[] = [
  {
    id: 'led-red',
    name: 'Red LED',
    category: 'LEDs and displays',
    description: 'Status indication and PWM brightness control.',
    interface: 'GPIO / PWM',
    partKind: 'passive',
    sourceUrl: 'https://docs.arduino.cc/built-in-examples/basics/Blink/',
    supplyRange: null,
    logicMax: null,
    addresses: [],
    notes: [
      '3.3 V or 5 V GPIO with a current-limiting resistor; check the LED forward voltage.',
      'Keep current below the LED and board per-pin/total limits; do not connect directly to the supply.',
    ],
    requires: ['Series current-limiting resistor'],
    template: 'led',
  },
  {
    id: 'led-rgb-cc',
    name: 'RGB LED — common cathode',
    category: 'LEDs and displays',
    description: 'Color mixing with three PWM channels.',
    interface: '3 × PWM',
    partKind: 'passive',
    sourceUrl:
      'https://learn.adafruit.com/adafruit-arduino-lesson-3-rgb-leds/overview',
    supplyRange: null,
    logicMax: null,
    addresses: [],
    notes: [
      'Each of the three channels needs a separate resistor; common-anode versions require different code.',
      "Check each LED channel and the board's total current limit separately.",
    ],
    requires: ['3 × series resistors'],
    template: 'rgb',
  },
  {
    id: 'resistor',
    name: 'Resistor',
    category: 'Passive components',
    description: 'Current limiting, voltage division, and RC filters.',
    interface: 'Analog',
    partKind: 'passive',
    sourceUrl: 'https://learn.sparkfun.com/tutorials/resistors/all',
    supplyRange: null,
    logicMax: null,
    addresses: [],
    notes: [
      'Logic level is not applicable.',
      'P = V²/R; power rating, tolerance, and voltage rating depend on the selected part.',
    ],
    requires: [],
    template: 'passive',
  },
  {
    id: 'ceramic-capacitor',
    name: 'Ceramic capacitor',
    category: 'Passive components',
    description: 'Supply bypassing and filtering capacitor.',
    interface: 'Analog',
    partKind: 'passive',
    sourceUrl: 'https://learn.sparkfun.com/tutorials/capacitors/all',
    supplyRange: null,
    logicMax: null,
    addresses: [],
    notes: [
      'Logic level is not applicable.',
      'Do not exceed the rated voltage; capacitance tolerance and DC-bias effects depend on the part type.',
    ],
    requires: [],
    template: 'passive',
  },
  {
    id: 'electrolytic-capacitor',
    name: 'Electrolytic capacitor',
    category: 'Passive components',
    description: 'Energy storage and ripple reduction on supply rails.',
    interface: 'Analog',
    partKind: 'passive',
    sourceUrl: 'https://learn.sparkfun.com/tutorials/capacitors/all',
    supplyRange: null,
    logicMax: null,
    addresses: [],
    notes: [
      'Logic level is not applicable.',
      'Polarized; avoid reverse connection. Voltage rating, ripple current, and ESR depend on the selected part.',
    ],
    requires: [],
    template: 'passive',
  },
  {
    id: 'pot-10k',
    name: '10 kΩ potentiometer',
    category: 'Inputs and switches',
    description: 'Analog user input from a rotary control.',
    interface: 'ADC',
    partKind: 'passive',
    sourceUrl:
      'https://docs.arduino.cc/built-in-examples/basics/AnalogReadSerial/',
    supplyRange: [0, 5],
    logicMax: null,
    addresses: [],
    notes: [
      'Connect the outer terminals to GND and a rail no higher than the ADC reference; connect the wiper to the ADC input.',
      'Power rating and wiper current depend on the selected part.',
      'Potentiometer: outer terminals to logic supply and GND; wiper to OUT. Resistive sensor: sensor between logic supply and OUT, fixed 10 kΩ resistor between OUT and GND; OUT to ADC input. The output is not calibrated in physical units.',
    ],
    requires: [],
    template: 'analog',
  },
  {
    id: 'pushbutton',
    name: 'Momentary pushbutton',
    category: 'Inputs and switches',
    description: 'Digital input for detecting button presses.',
    interface: 'GPIO',
    partKind: 'passive',
    sourceUrl:
      'https://docs.arduino.cc/built-in-examples/digital/InputPullupSerial/',
    supplyRange: null,
    logicMax: null,
    addresses: [],
    notes: [
      'Connect between the pin and GND using INPUT_PULLUP; active level is LOW.',
      'Debounce in software; do not wire the switch to short the supply rails.',
    ],
    requires: [],
    template: 'button',
  },
  {
    id: 'reed-switch',
    name: 'Magnetic reed switch',
    category: 'Inputs and switches',
    description: 'Detects a nearby magnet by opening or closing contacts.',
    interface: 'GPIO',
    partKind: 'passive',
    sourceUrl:
      'https://learn.sparkfun.com/tutorials/reed-switch-hookup-guide/all',
    supplyRange: null,
    logicMax: null,
    addresses: [],
    notes: [
      'Connect between the pin and GND using INPUT_PULLUP.',
      'The glass body is fragile; this profile uses it only as a low-current signal contact.',
    ],
    requires: ['Magnet'],
    template: 'button',
  },
  {
    id: 'ldr',
    name: 'LDR photoresistor',
    category: 'Light and environment',
    description: 'Relative light measurement from changes in resistance.',
    interface: 'ADC',
    partKind: 'passive',
    sourceUrl:
      'https://learn.sparkfun.com/tutorials/tinker-kit-circuit-guide/circuit-3-photoresistor',
    supplyRange: [0, 5],
    logicMax: null,
    addresses: [],
    notes: [
      'The voltage divider output must not exceed the ADC reference.',
      'This is not a lux measurement without calibration.',
      'Potentiometer: outer terminals to logic supply and GND; wiper to OUT. Resistive sensor: sensor between logic supply and OUT, fixed 10 kΩ resistor between OUT and GND; OUT to ADC input. The output is not calibrated in physical units.',
    ],
    requires: ['Fixed resistor for voltage divider'],
    template: 'analog',
  },
  {
    id: 'fsr',
    name: 'FSR force-sensitive resistor',
    category: 'Inputs and switches',
    description: 'Detects applied pressure and relative force changes.',
    interface: 'ADC',
    partKind: 'passive',
    sourceUrl:
      'https://learn.sparkfun.com/tutorials/force-sensitive-resistor-hookup-guide/all',
    supplyRange: [0, 5],
    logicMax: null,
    addresses: [],
    notes: [
      'Use a voltage divider at the same supply level as the ADC.',
      'For contact and relative force sensing, not precision weighing.',
      'Potentiometer: outer terminals to logic supply and GND; wiper to OUT. Resistive sensor: sensor between logic supply and OUT, fixed 10 kΩ resistor between OUT and GND; OUT to ADC input. The output is not calibrated in physical units.',
    ],
    requires: ['Voltage divider resistor'],
    template: 'analog',
  },
  {
    id: 'ntc-10k',
    name: '10 kΩ NTC thermistor',
    category: 'Temperature and environment',
    description: 'Estimates temperature from resistance changes.',
    interface: 'ADC',
    partKind: 'passive',
    sourceUrl: 'https://learn.adafruit.com/thermistor/using-a-thermistor',
    supplyRange: [0, 5],
    logicMax: null,
    addresses: [],
    notes: [
      'The voltage divider output must not exceed the ADC reference.',
      "Self-heating affects measurements; temperature calculations require the part's beta or Steinhart–Hart coefficients.",
      'This template reports only raw ADC/voltage readings; it does not calculate temperature without a beta coefficient and calibration.',
      'Potentiometer: outer terminals to logic supply and GND; wiper to OUT. Resistive sensor: sensor between logic supply and OUT, fixed 10 kΩ resistor between OUT and GND; OUT to ADC input. The output is not calibrated in physical units.',
    ],
    requires: ['10 kΩ precision series resistor'],
    template: 'analog',
  },
  {
    id: 'piezo-passive',
    name: 'Passive piezo buzzer',
    category: 'Audio',
    description: 'Generates alerts and notes with tone().',
    interface: 'GPIO / tone',
    partKind: 'passive',
    sourceUrl: 'https://docs.arduino.cc/built-in-examples/digital/toneMelody/',
    supplyRange: null,
    logicMax: null,
    addresses: [],
    notes: [
      "The drive signal amplitude must stay within the part's voltage rating.",
      'An active buzzer and a low-impedance speaker are different devices; check the GPIO current limit.',
    ],
    requires: ['Series resistor or driver if needed'],
    template: 'piezo',
  },
  {
    id: 'tmp36',
    name: 'Analog Devices TMP36',
    category: 'Temperature and environment',
    description: 'Temperature sensor with an analog voltage output.',
    interface: 'ADC',
    partKind: 'bare IC',
    sourceUrl:
      'https://www.analog.com/media/en/technical-documentation/data-sheets/tmp35_36_37.pdf',
    supplyRange: [2.7, 5.5],
    logicMax: null,
    addresses: [],
    notes: [
      'Analog output: 500 mV offset + 10 mV/°C; ADC input limits also apply.',
      'Supply current below 50 µA; do not use the output as a power source.',
    ],
    requires: ['Supply bypass capacitor'],
    template: 'tmp36',
  },
  {
    id: 'lm35',
    name: 'TI LM35',
    category: 'Temperature and environment',
    description: 'Simple analog measurement of positive temperatures.',
    interface: 'ADC',
    partKind: 'bare IC',
    sourceUrl: 'https://www.ti.com/product/LM35',
    supplyRange: [4, 30],
    logicMax: null,
    addresses: [],
    notes: [
      'Operation from a 3.3 V supply is not specified. Analog output is 10 mV/°C; respect ADC limits.',
      'A wide supply range does not permit high voltage on the Arduino ADC pin; negative temperatures require a different circuit.',
    ],
    requires: ['Supply bypass capacitor'],
    template: 'lm35',
  },
  {
    id: 'dht22',
    name: 'DHT22 — four-pin sensor',
    category: 'Temperature and environment',
    description:
      'Temperature and relative humidity sensor with a low sampling rate.',
    interface: 'Single-wire digital data',
    partKind: 'sensor',
    sourceUrl: 'https://learn.adafruit.com/dht/connecting-to-a-dhtxx-sensor',
    supplyRange: [3.3, 5],
    logicMax: null,
    addresses: [],
    notes: [
      "The data pull-up must match the controller's logic level; check the module variant.",
      'Allow at least 2 seconds between measurements.',
    ],
    requires: ['10 kΩ data-line pull-up'],
    template: 'dht22',
    library: 'DHT sensor library by Adafruit, Adafruit Unified Sensor',
  },
  {
    id: 'ds18b20',
    name: 'Analog Devices DS18B20',
    category: 'Temperature and environment',
    description: 'Addressable digital temperature sensor.',
    interface: '1-Wire',
    partKind: 'bare IC',
    sourceUrl:
      'https://www.analog.com/media/en/technical-documentation/data-sheets/DS18B20.pdf',
    supplyRange: [3, 5.5],
    logicMax: null,
    addresses: [],
    notes: [
      'With local power, the data pull-up must not exceed VDD; a 3.3 V local supply suits a 3.3 V host.',
      'Maximum 1.5 mA during conversion; the starter template uses three-wire local power instead of parasitic power.',
    ],
    requires: ['4.7 kΩ data pull-up resistor'],
    template: 'ds18b20',
    library: 'OneWire, DallasTemperature',
  },
  {
    id: 'bme280-bare',
    name: 'Bosch BME280 — bare IC',
    category: 'Temperature and environment',
    description:
      'Bare sensor IC measuring temperature, pressure, and humidity.',
    interface: 'I2C / SPI',
    partKind: 'bare IC',
    sourceUrl:
      'https://www.bosch-sensortec.com/media/boschsensortec/downloads/datasheets/bst-bme280-ds002.pdf',
    supplyRange: [1.71, 3.6],
    logicMax: 3.3,
    addresses: [],
    notes: [
      'VDDIO 1.2–3.6 V; not 5 V tolerant.',
      'Typical humidity/pressure/temperature measurement current is 3.6 µA at 1 Hz; this is not a breakout board.',
      'No fixed default: SDO=GND → 0x76; SDO=VDDIO → 0x77.',
    ],
    requires: [
      'PCB adapter',
      'Bypass capacitors',
      'Suitable I2C pull-ups',
      'Level shifter for a 5 V host',
    ],
  },
  {
    id: 'bme280-adafruit',
    name: 'Adafruit BME280 breakout',
    category: 'Temperature and environment',
    description:
      'Read ambient temperature, humidity, and pressure with Arduino.',
    interface: 'I2C / SPI',
    partKind: 'named breakout',
    sourceUrl:
      'https://learn.adafruit.com/adafruit-bme280-humidity-barometric-pressure-temperature-sensor-breakout/pinouts',
    supplyRange: [3, 5],
    logicMax: null,
    addresses: [119, 118],
    notes: [
      '3–5 V logic matched to VIN; onboard regulation and level shifting.',
      'SDO to GND or ADDR jumper closed → 0x76.',
    ],
    requires: [],
    template: 'bme280',
    library: 'Adafruit BME280 Library, Adafruit Unified Sensor',
  },
  {
    id: 'bmp280-adafruit',
    name: 'Adafruit BMP280 breakout',
    category: 'Temperature and environment',
    description: 'Pressure and temperature measurement; no humidity sensor.',
    interface: 'I2C / SPI',
    partKind: 'named breakout',
    sourceUrl:
      'https://learn.adafruit.com/adafruit-bmp280-barometric-pressure-plus-temperature-sensor-breakout?view=all',
    supplyRange: [3, 5],
    logicMax: null,
    addresses: [119, 118],
    notes: [
      '3–5 V input level shifting; connect VIN to the host logic supply.',
      "Default 0x77; select 0x76 using the board's SDO/ADDR connection. Check the board revision.",
    ],
    requires: [],
    template: 'bmp280',
    library: 'Adafruit BMP280 Library',
  },
  {
    id: 'bh1750-adafruit',
    name: 'Adafruit BH1750 breakout',
    category: 'Light and environment',
    description: 'Digital ambient light sensor.',
    interface: 'I2C',
    partKind: 'named breakout',
    sourceUrl:
      'https://learn.adafruit.com/adafruit-bh1750-ambient-light-sensor?view=all',
    supplyRange: [3, 5],
    logicMax: null,
    addresses: [35, 92],
    notes: [
      "Match VIN to the host's 3.3 V or 5 V logic rail.",
      'ADDR high or AD0 jumper closed → 0x5C.',
    ],
    requires: [],
  },
  {
    id: 'mpu6050-adafruit',
    name: 'Adafruit MPU6050 breakout',
    category: 'Motion and IMU',
    description:
      'Three-axis acceleration and three-axis angular velocity measurement.',
    interface: 'I2C',
    partKind: 'named breakout',
    sourceUrl:
      'https://learn.adafruit.com/mpu6050-6-dof-accelerometer-and-gyro/pinouts',
    supplyRange: [3, 5],
    logicMax: null,
    addresses: [104, 105],
    notes: [
      'This Adafruit board supports 3–5 V power/logic; this does not generalize to bare MPU6050 chips or generic GY-521 boards.',
      'AD0 high → 0x69; the default address conflicts with DS3231.',
    ],
    requires: [],
    template: 'mpu6050',
    library: 'Adafruit MPU6050, Adafruit Unified Sensor',
  },
  {
    id: 'hcsr04-5v-sparkfun',
    name: 'HC-SR04 5 V — SparkFun SEN-15569',
    category: 'Distance',
    description: 'Distance measurement using ultrasonic time of flight.',
    interface: 'Trigger / Echo',
    partKind: 'named module',
    sourceUrl:
      'https://www.sparkfun.com/ultrasonic-distance-sensor-hc-sr04.html',
    supplyRange: [5, 5],
    logicMax: null,
    addresses: [],
    notes: [
      'Treat ECHO as a 5 V signal; do not connect it directly to a 3.3 V input.',
      'Approximately 15 mA; nominal range 2 cm–4 m; results depend on the surface and environment.',
    ],
    requires: ['Resistor divider/level shifter for ECHO on a 3.3 V host'],
    template: 'hcsr04',
  },
  {
    id: 'vl53l0x-adafruit',
    name: 'Adafruit VL53L0X breakout',
    category: 'Distance',
    description: 'Distance measurement using optical time of flight.',
    interface: 'I2C',
    partKind: 'named breakout',
    sourceUrl:
      'https://learn.adafruit.com/adafruit-vl53l0x-micro-lidar-distance-sensor-breakout/arduino-code',
    supplyRange: [3, 5],
    logicMax: null,
    addresses: [41],
    notes: [
      "The board's I2C interface supports 3–5 V hosts; check the pinout limits for XSHUT separately.",
      'Multiple sensors with the same address are started sequentially using XSHUT and reassigned addresses.',
      'The address is changed in software and resets to default after power is removed.',
    ],
    requires: ['Separate XSHUT GPIO for each additional sensor'],
    template: 'vl53l0x',
    library: 'Adafruit_VL53L0X',
  },
  {
    id: 'ssd1306-adafruit-128x64',
    name: 'Adafruit SSD1306 OLED 128×64 — 5V-ready version',
    category: 'LEDs and displays',
    description: 'Compact display for graphics, text, and sensor data.',
    interface: 'I2C / SPI',
    partKind: 'named breakout',
    sourceUrl: 'https://learn.adafruit.com/monochrome-oled-breakouts?view=all',
    supplyRange: [3, 5],
    logicMax: null,
    addresses: [61, 60],
    notes: [
      'Only the Adafruit version labeled 5V-ready; the older v1 0.96-inch board is not 5 V compatible.',
      'Typical consumption depends on displayed content; a full 128×64 framebuffer needs 1024 bytes of RAM.',
      '0x3D for this 128×64 variant; check jumpers/revision and run an I2C scan.',
    ],
    requires: [
      'RESET GPIO and interface jumper settings for the board revision',
    ],
    template: 'ssd1306',
    library: 'Adafruit SSD1306, Adafruit GFX Library',
  },
  {
    id: 'lcd-backpack-adafruit',
    name: 'Adafruit I2C/SPI LCD backpack — boost-circuit version',
    category: 'LEDs and displays',
    description: 'Drive a character LCD using fewer GPIO pins.',
    interface: 'I2C / SPI',
    partKind: 'named breakout',
    sourceUrl: 'https://learn.adafruit.com/i2c-spi-lcd-backpack?view=all',
    supplyRange: [3, 5],
    logicMax: null,
    addresses: [32, 33, 34, 35, 36, 37, 38, 39],
    notes: [
      'The specified newer board supports 3–5 V power/logic and a 5 V boost supply for the LCD.',
      'LCD and backlight consumption depend on the connected display model.',
      'A0/A1/A2 jumpers set the address.',
    ],
    requires: ['Compatible 16-pin character LCD'],
  },
  {
    id: 'ds3231-adafruit',
    name: 'Adafruit DS3231 RTC breakout',
    category: 'Storage and time',
    description: 'Real-time clock that retains time with a backup battery.',
    interface: 'I2C',
    partKind: 'named breakout',
    sourceUrl:
      'https://learn.adafruit.com/adafruit-ds3231-precision-rtc-breakout?view=all',
    supplyRange: [2.3, 5.5],
    logicMax: null,
    addresses: [104],
    notes: [
      'SDA/SCL pull-ups use VIN; match VIN to the host logic level.',
      'The battery type must suit the board revision.',
      'The address cannot be changed; it may conflict with MPU6050.',
    ],
    requires: ['Optional compatible backup coin cell'],
    template: 'ds3231',
    library: 'RTClib by Adafruit',
  },
  {
    id: 'mcp4725-adafruit',
    name: 'Adafruit MCP4725 DAC breakout — A1',
    category: 'ADC, DAC, and analog',
    description: 'Generates an analog output voltage from 12-bit digital data.',
    interface: 'I2C',
    partKind: 'named breakout',
    sourceUrl: 'https://learn.adafruit.com/mcp4725-12-bit-dac-tutorial/pinouts',
    supplyRange: [2.7, 5.5],
    logicMax: null,
    addresses: [98, 99],
    notes: [
      '3–5 V I2C logic; choose a host matched to VIN. VOUT is approximately 0–VIN.',
      'An analog signal output; it does not directly power motors, speakers, or similar loads.',
      'A0 high or ADDR closed → 0x63; other MCP4725 ordering variants may use different addresses.',
    ],
    requires: ['Output buffer suited to the load'],
    template: 'mcp4725',
    library: 'Adafruit MCP4725',
  },
  {
    id: 'ads1115-adafruit',
    name: 'Adafruit ADS1115 ADC breakout',
    category: 'ADC, DAC, and analog',
    description: 'Four-input 16-bit analog-to-digital converter.',
    interface: 'I2C',
    partKind: 'named breakout',
    sourceUrl:
      'https://learn.adafruit.com/adafruit-4-channel-adc-breakouts/pinouts',
    supplyRange: [2, 5],
    logicMax: null,
    addresses: [72, 73, 74, 75],
    notes: [
      'VIN must match the host logic level; keep analog ADC inputs within GND–VIN.',
      'Selecting a ±6.144 V PGA full-scale range does not allow inputs to exceed the supply rails.',
      'ADDR: GND=0x48, VIN=0x49, SDA=0x4A, SCL=0x4B.',
    ],
    requires: ['Voltage divider/protection if required by the input'],
    template: 'ads1115',
    library: 'Adafruit ADS1X15',
  },
  {
    id: 'pca9685-adafruit',
    name: 'Adafruit PCA9685 16-channel PWM/servo breakout',
    category: 'Motors and drivers',
    description: '16 channels of 12-bit PWM output.',
    interface: 'I2C',
    partKind: 'named breakout',
    sourceUrl:
      'https://learn.adafruit.com/16-channel-pwm-servo-driver?view=all',
    supplyRange: [3, 5],
    logicMax: null,
    addresses: [64],
    notes: [
      'VCC is the logic rail and sets I2C pull-up voltage and PWM amplitude. V+ is a separate load supply.',
      'V+ is typically 5–6 V for servos; do not supply motor power through Arduino GPIO or logic VCC.',
      'A0–A5 select the main address. The 7-bit 0x70 ALLCALL address is also active at startup; separately check for conflicts with 0x70 devices such as TCA9548A.',
    ],
    requires: [
      'External servo supply',
      'Common GND',
      'Bulk capacitor suited to the load',
    ],
    additionalAddresses: [112],
  },
  {
    id: 'neopixel-ws2812b',
    name: 'WS2812B-based NeoPixel RGB chain',
    category: 'LEDs and displays',
    description: 'Addressable RGB LED animations.',
    interface: 'Timing-sensitive single data line',
    partKind: 'named module',
    sourceUrl:
      'https://learn.adafruit.com/adafruit-neopixel-uberguide/best-practices',
    supplyRange: [5, 5],
    logicMax: null,
    addresses: [],
    notes: [
      'Use 5 V data for a 5 V-powered chain; a 3.3 V host needs a suitable level shifter such as 74AHCT125.',
      'Current depends on pixel model, color, and brightness; large chains need a separate supply. Do not assume all WS2812 revisions have identical electrical limits.',
    ],
    requires: [
      '300–500 Ω data resistor',
      '500–1000 µF bulk capacitor, rated at least 6.3 V',
      'Suitable external 5 V supply',
      'Logic level shifter if needed',
    ],
  },
  {
    id: 'tb6612fng-sparkfun',
    name: 'SparkFun TB6612FNG dual motor driver',
    category: 'Motors and drivers',
    description:
      'Direction, speed, braking, and stop control for two brushed DC motors.',
    interface: 'GPIO / PWM',
    partKind: 'named breakout',
    sourceUrl:
      'https://learn.sparkfun.com/tutorials/tb6612fng-hookup-guide/all',
    supplyRange: [2.7, 5.5],
    logicMax: null,
    addresses: [],
    notes: [
      'VCC is 2.7–5.5 V logic; VM is a separate motor supply.',
      'VM operating range 2.5–13.5 V; 1.2 A continuous / brief 3.2 A peak per channel. Evaluate stall current and thermal conditions.',
    ],
    requires: [
      'External VM supply suited to the motor',
      'Common GND',
      'STBY control',
    ],
  },
  {
    id: 'drv8833-adafruit',
    name: 'Adafruit DRV8833 motor driver breakout',
    category: 'Motors and drivers',
    description: 'Drives two DC motors or one bipolar stepper motor.',
    interface: 'GPIO / PWM',
    partKind: 'named breakout',
    sourceUrl:
      'https://learn.adafruit.com/adafruit-drv8833-dc-stepper-motor-driver-breakout-board',
    supplyRange: [2.7, 10.8],
    logicMax: null,
    addresses: [],
    notes: [
      'For 3.3 V and 5 V GPIO control; VM load power is separate from GPIO pins.',
      'Approximately 1.2 A continuous for this breakout; 2 A only for brief peaks with suitable current limiting.',
    ],
    requires: ['Suitable motor and external supply', 'Common GND'],
  },
  {
    id: 'a4988-pololu',
    name: 'Pololu A4988 Stepper Motor Driver Carrier',
    category: 'Motors and drivers',
    description: 'Current-limited microstepping for bipolar stepper motors.',
    interface: 'STEP / DIR',
    partKind: 'named breakout',
    sourceUrl: 'https://www.pololu.com/product/1182',
    supplyRange: [3, 5.5],
    logicMax: null,
    addresses: [],
    notes: [
      'VDD is 3–5.5 V logic; VMOT is a separate 8–35 V motor supply.',
      'Approximately 1 A per phase without extra cooling; 2 A requires adequate cooling. Set the current limit with VREF; do not disconnect the motor while powered.',
    ],
    requires: [
      'Bipolar stepper motor',
      'External 8–35 V VMOT supply',
      'At least 47 µF electrolytic capacitor close to VMOT',
      'Current-limit adjustment',
    ],
  },
  {
    id: 'hobby-servo',
    name: 'Hobby servo — select a specific model',
    category: 'Motors and drivers',
    description:
      'Pulse-width control of position or continuous rotation speed.',
    interface: 'Servo pulse signal',
    partKind: 'actuator',
    sourceUrl:
      'https://support.arduino.cc/hc/en-us/articles/360017053760-Troubleshoot-servo-motors',
    supplyRange: null,
    logicMax: null,
    addresses: [],
    notes: [
      "Verify the signal threshold and pulse range in the selected servo's datasheet.",
      'Size the external supply for stall current; Arduino and the servo supply share GND.',
    ],
    requires: [
      'Datasheet for the specific servo',
      'Suitable external supply',
      'Common GND',
    ],
  },
  {
    id: 'microsd-adafruit-254',
    name: 'Adafruit microSD breakout — product 254',
    category: 'Storage and time',
    description: 'Data logging to an SD card over SPI.',
    interface: 'SPI',
    partKind: 'named breakout',
    sourceUrl: 'https://www.adafruit.com/product/254',
    supplyRange: null,
    logicMax: null,
    addresses: [],
    notes: [
      'Board with regulator and input level shifting for 3.3 V / 5 V hosts; DO is a 3.3 V output from the board.',
      'The supply must handle write-current peaks; verify the use of the 3V and 5V pins in the board guide.',
    ],
    requires: ['FAT-compatible microSD card'],
  },
  {
    id: 'microsd-adafruit-4682',
    name: 'Adafruit microSD SPI/SDIO breakout — product 4682',
    category: 'Storage and time',
    description: 'Direct microSD interface for 3.3 V systems.',
    interface: 'SPI / SDIO',
    partKind: 'named breakout',
    sourceUrl: 'https://www.adafruit.com/product/4682',
    supplyRange: [3.3, 3.3],
    logicMax: 3.3,
    addresses: [],
    notes: [
      '3.3 V power and logic only; no regulator or level shifter.',
      'Do not apply 5 V power or logic; check supply capacity for write current.',
    ],
    requires: ['microSD card', 'Suitable level shifting for a 5 V host'],
  },
  {
    id: 'sht31-adafruit',
    name: 'Adafruit SHT31-D breakout',
    category: 'Temperature and environment',
    description: 'Digital temperature and relative humidity measurement.',
    interface: 'I2C',
    partKind: 'named breakout',
    sourceUrl:
      'https://learn.adafruit.com/adafruit-sht31-d-temperature-and-humidity-sensor-breakout/pinouts',
    supplyRange: [2.5, 5],
    logicMax: null,
    addresses: [68, 69],
    notes: [
      'SDA/SCL have 10 kΩ pull-ups to VIN; match the host logic rail.',
      'ADR VIN → 0x45.',
    ],
    requires: [],
  },
  {
    id: 'aht20-adafruit',
    name: 'Adafruit AHT20 breakout',
    category: 'Temperature and environment',
    description: 'Temperature and humidity sensor with a fixed address.',
    interface: 'I2C',
    partKind: 'named breakout',
    sourceUrl: 'https://learn.adafruit.com/adafruit-aht20/pinouts',
    supplyRange: [2.7, 5.5],
    logicMax: null,
    addresses: [56],
    notes: [
      'Logic level follows VIN; SDA/SCL have 10 kΩ pull-ups.',
      'The address cannot be changed.',
    ],
    requires: [],
  },
  {
    id: 'ina219-adafruit',
    name: 'Adafruit INA219 breakout',
    category: 'ADC, DAC, and analog',
    description: 'Monitors current, bus voltage, and power using a shunt.',
    interface: 'I2C',
    partKind: 'named breakout',
    sourceUrl:
      'https://learn.adafruit.com/adafruit-ina219-current-sensor-breakout?view=all',
    supplyRange: [2.7, 5.5],
    logicMax: null,
    addresses: [64, 65, 68, 69],
    notes: [
      'VIN is the logic supply and differs from the VIN+/VIN− current-measurement path. Match the host logic level.',
      'The measured DC bus must not exceed 26 V; evaluate shunt resistance/power and inductive transients separately.',
      'A0/A1 jumper combinations; the default address conflicts with PCA9685.',
    ],
    requires: ['Low-voltage load circuit to measure'],
  },
  {
    id: 'tca9548a-adafruit',
    name: 'Adafruit TCA9548A I2C multiplexer',
    category: 'Logic and connectivity',
    description: 'Uses sensors with the same address on separate I2C channels.',
    interface: 'I2C',
    partKind: 'named breakout',
    sourceUrl:
      'https://learn.adafruit.com/adafruit-tca9548a-1-to-8-i2c-multiplexer-breakout/pinouts',
    supplyRange: [3, 5],
    logicMax: null,
    addresses: [112, 113, 114, 115, 116, 117, 118, 119],
    notes: [
      'Each downstream I2C bus needs a suitable pull-up rail.',
      'Do not enable downstream channels with conflicting addresses simultaneously; account for all pull-up loads.',
      'Selected with A0/A1/A2.',
    ],
    requires: ['Downstream I2C pull-up resistors if needed'],
  },
  {
    id: 'max9814-adafruit',
    name: 'Adafruit MAX9814 AGC microphone breakout',
    category: 'Audio',
    description: 'Microphone signal with automatic gain control.',
    interface: 'ADC',
    partKind: 'named breakout',
    sourceUrl:
      'https://learn.adafruit.com/adafruit-agc-electret-microphone-amplifier-max9814',
    supplyRange: [2.7, 5.5],
    logicMax: null,
    addresses: [],
    notes: [
      "The analog output's DC offset and amplitude must fit within the ADC range.",
      'Not a calibrated sound-pressure meter; evaluate sampling rate and aliasing.',
    ],
    requires: [],
  },
  {
    id: 'pam8302-adafruit',
    name: 'Adafruit PAM8302 mono amplifier',
    category: 'Audio',
    description: 'Amplifies an analog audio signal to drive a speaker.',
    interface: 'Analog audio',
    partKind: 'named breakout',
    sourceUrl:
      'https://learn.adafruit.com/adafruit-pam8302-mono-2-5w-class-d-audio-amplifier/pinouts',
    supplyRange: [2, 5.5],
    logicMax: null,
    addresses: [],
    notes: [
      'A+/A− are analog inputs; no digital communication or I2C.',
      'Connect both bridge-output terminals directly to the speaker; neither speaker output connects to GND.',
    ],
    requires: [
      'Compatible speaker',
      'Suitable power supply',
      'Analog audio source',
    ],
    template: 'passive',
  },
  {
    id: 'lm358',
    name: 'TI LM358 — classic variant',
    category: 'ADC, DAC, and analog',
    description: 'Dual general-purpose operational amplifier.',
    interface: 'Analog',
    partKind: 'bare IC',
    sourceUrl: 'https://www.ti.com/product/LM358',
    supplyRange: [3, 30],
    logicMax: null,
    addresses: [],
    notes: [
      'Not a logic interface; check input common-mode range and output swing relative to the supply rails.',
      'Input and output do not reach the positive rail; variants such as LM358B have different limits.',
    ],
    requires: ['Bypass capacitor', 'Feedback resistors'],
    template: 'passive',
  },
  {
    id: 'sn74hc595',
    name: 'TI SN74HC595',
    category: 'Logic and connectivity',
    description: 'Converts serial data to eight parallel digital outputs.',
    interface: 'Shift register / SPI-like',
    partKind: 'bare IC',
    sourceUrl: 'https://www.ti.com/product/SN74HC595',
    supplyRange: [2, 6],
    logicMax: null,
    addresses: [],
    notes: [
      'HC CMOS input thresholds depend on supply voltage; a 3.3 V HIGH is not guaranteed with a 5 V supply.',
      'Not a power driver for motors or LED strips; check per-output and total package current limits.',
    ],
    requires: ['100 nF bypass', 'One resistor per channel when using LEDs'],
  },
  {
    id: 'bss138-adafruit',
    name: 'Adafruit BSS138 4-channel level shifter',
    category: 'Logic and connectivity',
    description: 'Bidirectional level shifting for open-drain I2C lines.',
    interface: 'I2C / low-speed digital',
    partKind: 'named breakout',
    sourceUrl: 'https://www.adafruit.com/product/757',
    supplyRange: null,
    logicMax: null,
    addresses: [],
    notes: [
      'Low side down to 1.8 V; high side up to 10 V. Connect both supply rails.',
      '10 kΩ pull-ups limit edge rates; this is not a general-purpose solution for driving loads or high-speed SPI.',
    ],
    requires: ['Low-side and high-side logic supply rails', 'Common GND'],
    template: 'passive',
  },
  {
    id: 'flex-sensor',
    name: 'Flex bend sensor',
    category: 'Inputs and switches',
    description: 'Tracks resistance changes caused by bending.',
    interface: 'ADC',
    partKind: 'passive',
    sourceUrl:
      'https://learn.sparkfun.com/tutorials/flex-sensor-hookup-guide/example-circuit',
    supplyRange: [0, 5],
    logicMax: null,
    addresses: [],
    notes: [
      'The voltage divider output must not exceed the ADC reference.',
      'Requires calibration and mechanical repeatability.',
      'Potentiometer: outer terminals to logic supply and GND; wiper to OUT. Resistive sensor: sensor between logic supply and OUT, fixed 10 kΩ resistor between OUT and GND; OUT to ADC input. The output is not calibrated in physical units.',
    ],
    requires: ['Fixed resistor for voltage divider'],
    template: 'analog',
  },
  {
    id: 'filter-output',
    name: 'Sallen–Key filter output',
    category: 'Analog and filters',
    description:
      'Add a Filter AI design to an ADC measurement plan. Logs voltage slowly; it does not measure frequency response.',
    interface: 'Analog',
    partKind: 'virtual-interface',
    supplyRange: null,
    logicMax: null,
    addresses: [],
    sourceUrl:
      'https://docs.arduino.cc/language-reference/en/functions/analog-io/analogRead/',
    notes: [
      "Build the filter circuit separately. Connect OUT to the Arduino ADC pin and share reference GND. The input must not be negative or exceed the board's ADC range.",
    ],
    requires: [
      'R1, R2, C1, C2',
      'Suitable unity-gain-stable op-amp',
      'Biasing and ADC protection if needed',
    ],
    template: 'filter',
  },
];
