export type ProductImage = {
  src: string;
  sourcePage: string;
  attribution: string;
  match: 'exact' | 'representative';
  note?: string;
  imageKind?: string;
  licenseUrl?: string;
  license?: string;
};
export const productImages: Record<string, ProductImage> = {
  'esp32-devkitc-v4': {
    src: '/products/esp32-devkitc-v4.webp',
    sourcePage:
      'https://docs.espressif.com/projects/esp-dev-kits/en/latest/esp32/esp32-devkitc/user_guide.html',
    attribution:
      'Photo: Espressif Systems (Shanghai) Co., Ltd., esp-dev-kits documentation, CC BY-SA 4.0.',
    match: 'exact',
    note: 'Manufacturer-annotated product photograph; resized and converted to WebP.',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
  },
  'raspberry-pi-pico': {
    src: '/products/raspberry-pi-pico.webp',
    sourcePage:
      'https://www.raspberrypi.com/documentation/computers/raspberry-pi.html#pico-microcontroller-boards',
    attribution:
      'Photo: Raspberry Pi Ltd, Raspberry Pi documentation, CC BY-SA 4.0.',
    match: 'exact',
    note: 'Original RP2040 Pico, without a wireless module or soldered headers. Resized and converted to WebP.',
    license: 'CC BY-SA 4.0',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
  },

  'uno-rev3': {
    src: '/products/uno-rev3.webp',
    sourcePage: 'https://store.arduino.cc/products/arduino-uno-rev3/',
    attribution: 'Arduino',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'uno-rev3-smd': {
    src: '/products/uno-rev3-smd.webp',
    sourcePage: 'https://store.arduino.cc/products/arduino-uno-rev3-smd',
    attribution: 'Arduino',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'uno-mini-limited-edition': {
    src: '/products/uno-mini-limited-edition.webp',
    sourcePage:
      'https://support.arduino.cc/hc/en-us/articles/7901453165724-An-overview-of-different-UNO-boards',
    attribution: 'Arduino — official Help Center product photograph',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'uno-r4-minima': {
    src: '/products/uno-r4-minima.webp',
    sourcePage: 'https://store.arduino.cc/products/uno-r4-minima',
    attribution: 'Arduino',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'uno-r4-wifi': {
    src: '/products/uno-r4-wifi.webp',
    sourcePage: 'https://store.arduino.cc/products/uno-r4-wifi',
    attribution: 'Arduino',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'uno-wifi-rev2': {
    src: '/products/uno-wifi-rev2.webp',
    sourcePage: 'https://store.arduino.cc/products/arduino-uno-wifi-rev2',
    attribution: 'Arduino',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'uno-q': {
    src: '/products/uno-q.webp',
    sourcePage: 'https://store.arduino.cc/products/uno-q',
    attribution: 'Arduino',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP. The photographed version has 2 GB RAM.',
    imageKind: 'photograph',
  },
  nano: {
    src: '/products/nano.webp',
    sourcePage: 'https://store.arduino.cc/products/arduino-nano',
    attribution: 'Arduino',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'nano-every': {
    src: '/products/nano-every.webp',
    sourcePage: 'https://store.arduino.cc/products/nano-every',
    attribution: 'Arduino',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'nano-esp32': {
    src: '/products/nano-esp32.webp',
    sourcePage: 'https://store.arduino.cc/products/nano-esp32',
    attribution: 'Arduino',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP. The photographed version has no headers.',
    imageKind: 'photograph',
  },
  'nano-33-ble': {
    src: '/products/nano-33-ble.webp',
    sourcePage: 'https://store.arduino.cc/products/arduino-nano-33-ble',
    attribution: 'Arduino',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'nano-33-ble-rev2': {
    src: '/products/nano-33-ble-rev2.webp',
    sourcePage: 'https://store.arduino.cc/products/nano-33-ble-rev2',
    attribution: 'Arduino',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'nano-33-ble-sense': {
    src: '/products/nano-33-ble-sense.webp',
    sourcePage: 'https://docs.arduino.cc/hardware/nano-33-ble-sense/',
    attribution:
      'Arduino — product photograph embedded in official ABX00031 datasheet, page 1',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'nano-33-ble-sense-rev2': {
    src: '/products/nano-33-ble-sense-rev2.webp',
    sourcePage: 'https://store.arduino.cc/products/nano-33-ble-sense-rev2',
    attribution: 'Arduino',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'nano-33-iot': {
    src: '/products/nano-33-iot.webp',
    sourcePage: 'https://store.arduino.cc/products/arduino-nano-33-iot',
    attribution: 'Arduino',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'nano-rp2040-connect': {
    src: '/products/nano-rp2040-connect.webp',
    sourcePage:
      'https://store.arduino.cc/collections/interactive-games/products/arduino-nano-rp2040-connect',
    attribution: 'Arduino',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'nano-matter': {
    src: '/products/nano-matter.webp',
    sourcePage:
      'https://store.arduino.cc/collections/boards-modules/products/nano-matter?_fid=2db07d58d&_pos=9&_ss=c',
    attribution: 'Arduino',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'nano-r4': {
    src: '/products/nano-r4.webp',
    sourcePage: 'https://store.arduino.cc/products/nano-r4',
    attribution: 'Arduino',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'mega-2560': {
    src: '/products/mega-2560.webp',
    sourcePage: 'https://store.arduino.cc/products/arduino-mega-2560-rev3',
    attribution: 'Arduino',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  due: {
    src: '/products/due.webp',
    sourcePage: 'https://store.arduino.cc/products/arduino-due',
    attribution: 'Arduino',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'giga-r1-wifi': {
    src: '/products/giga-r1-wifi.webp',
    sourcePage: 'https://store.arduino.cc/products/giga-r1-wifi',
    attribution: 'Arduino',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  leonardo: {
    src: '/products/leonardo.webp',
    sourcePage:
      'https://store.arduino.cc/products/arduino-leonardo-with-headers',
    attribution: 'Arduino',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  micro: {
    src: '/products/micro.webp',
    sourcePage: 'https://store.arduino.cc/products/arduino-micro',
    attribution: 'Arduino',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  zero: {
    src: '/products/zero.webp',
    sourcePage: 'https://store.arduino.cc/products/arduino-zero',
    attribution: 'Arduino',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'yun-rev2': {
    src: '/products/yun-rev2.webp',
    sourcePage: 'https://blog.arduino.cc/2018/03/29/arduino-yun-rev-2-is-here/',
    attribution: 'Arduino',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'mkr-1000-wifi': {
    src: '/products/mkr-1000-wifi.webp',
    sourcePage: 'https://store-usa.arduino.cc/products/arduino-mkr1000-wifi',
    attribution: 'Arduino',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'mkr-wifi-1010': {
    src: '/products/mkr-wifi-1010.webp',
    sourcePage: 'https://store.arduino.cc/products/arduino-mkr-wifi-1010',
    attribution: 'Arduino',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'mkr-fox-1200': {
    src: '/products/mkr-fox-1200.webp',
    sourcePage:
      'https://blog.arduino.cc/2017/04/18/introducing-the-arduino-mkrfox1200/',
    attribution: 'Arduino',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'mkr-gsm-1400': {
    src: '/products/mkr-gsm-1400.webp',
    sourcePage:
      'https://solectroshop.com/en/placas-arduino-original/2013-arduino-mkr-gsm-1400.html',
    attribution: 'Solectroshop — Arduino MKR GSM 1400 product photograph',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'mkr-nb-1500': {
    src: '/products/mkr-nb-1500.webp',
    sourcePage:
      'https://store-usa.arduino.cc/collections/maker-solutions/products/arduino-mkr-nb-1500',
    attribution: 'Arduino',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'mkr-wan-1300': {
    src: '/products/mkr-wan-1300.webp',
    sourcePage:
      'https://www.electrokit.com/en/arduino-mkr-wan-1300-utan-antenn',
    attribution: 'Electrokit — Arduino MKR WAN 1300 product photograph',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'mkr-wan-1310': {
    src: '/products/mkr-wan-1310.webp',
    sourcePage: 'https://store.arduino.cc/products/arduino-mkr-wan-1310',
    attribution: 'Arduino',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'mkr-vidor-4000': {
    src: '/products/mkr-vidor-4000.webp',
    sourcePage:
      'https://blog.arduino.cc/2018/05/17/say-hello-to-the-next-generation-of-arduino-boards/',
    attribution: 'Arduino',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'mkr-zero': {
    src: '/products/mkr-zero.webp',
    sourcePage:
      'https://store.arduino.cc/products/arduino-mkr-zero-i2s-bus-sd-for-sound-music-digital-audio-data',
    attribution: 'Arduino',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'portenta-h7': {
    src: '/products/portenta-h7.webp',
    sourcePage: 'https://store.arduino.cc/products/portenta-h7',
    attribution: 'Arduino',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'portenta-h7-lite': {
    src: '/products/portenta-h7-lite.webp',
    sourcePage: 'https://store.arduino.cc/products/portenta-h7-lite',
    attribution: 'Arduino',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'portenta-h7-lite-connected': {
    src: '/products/portenta-h7-lite-connected.webp',
    sourcePage: 'https://store.arduino.cc/products/portenta-h7-lite-connected',
    attribution: 'Arduino',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'portenta-c33': {
    src: '/products/portenta-c33.webp',
    sourcePage: 'https://store.arduino.cc/products/portenta-c33',
    attribution: 'Arduino',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'portenta-x8': {
    src: '/products/portenta-x8.webp',
    sourcePage: 'https://store.arduino.cc/products/portenta-x8',
    attribution: 'Arduino',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'nicla-sense-me': {
    src: '/products/nicla-sense-me.webp',
    sourcePage: 'https://store.arduino.cc/products/nicla-sense-me',
    attribution: 'Arduino',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'nicla-vision': {
    src: '/products/nicla-vision.webp',
    sourcePage: 'https://store.arduino.cc/products/nicla-vision',
    attribution: 'Arduino',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'nicla-voice': {
    src: '/products/nicla-voice.webp',
    sourcePage: 'https://store.arduino.cc/products/nicla-voice',
    attribution: 'Arduino',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'arduino-101': {
    src: '/products/arduino-101.webp',
    sourcePage: 'https://docs.arduino.cc/retired/boards/arduino-101-619/',
    attribution: 'Arduino',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'arduino-duemilanove': {
    src: '/products/arduino-duemilanove.webp',
    sourcePage: 'https://docs.arduino.cc/retired/boards/arduino-duemilanove/',
    attribution: 'Arduino',
    match: 'representative',
    note: 'Official Arduino photograph. Do not infer logic voltage, clock speed, or processor variant from the image. Resized for the web.',
    imageKind: 'photograph',
  },
  'arduino-pro-mini': {
    src: '/products/arduino-pro-mini.webp',
    sourcePage: 'https://docs.arduino.cc/retired/boards/arduino-pro-mini/',
    attribution: 'Arduino',
    match: 'representative',
    note: 'Official Arduino photograph. Do not infer logic voltage, clock speed, or processor variant from the image. Resized for the web.',
    imageKind: 'photograph',
  },
  'led-red': {
    src: '/products/led-red.webp',
    sourcePage: 'https://www.sparkfun.com/led-basic-red-5mm.html',
    attribution: 'SparkFun Electronics',
    match: 'representative',
    note: 'Image resized for the web and converted to WebP. Manufacturer, package, or component values may differ.',
    imageKind: 'photograph',
  },
  'led-rgb-cc': {
    src: '/products/led-rgb-cc.webp',
    sourcePage: 'https://www.sparkfun.com/led-rgb-clear-common-cathode.html',
    attribution: 'SparkFun Electronics',
    match: 'representative',
    note: 'Image resized for the web and converted to WebP. Manufacturer, package, or component values may differ.',
    imageKind: 'photograph',
  },
  resistor: {
    src: '/products/resistor.webp',
    sourcePage:
      'https://www.sparkfun.com/resistor-10k-ohm-1-4-watt-pth-20-pack-thick-leads.html',
    attribution: 'SparkFun Electronics',
    match: 'representative',
    note: 'Image resized for the web and converted to WebP. Manufacturer, package, or component values may differ.',
    imageKind: 'photograph',
  },
  'ceramic-capacitor': {
    src: '/products/ceramic-capacitor.webp',
    sourcePage: 'https://www.sparkfun.com/capacitor-ceramic-0-1uf.html',
    attribution: 'SparkFun Electronics',
    match: 'representative',
    note: 'Image resized for the web and converted to WebP. Manufacturer, package, or component values may differ.',
    imageKind: 'photograph',
  },
  'electrolytic-capacitor': {
    src: '/products/electrolytic-capacitor.webp',
    sourcePage:
      'https://www.sparkfun.com/electrolytic-decoupling-capacitors-100uf-25v.html',
    attribution: 'SparkFun Electronics',
    match: 'representative',
    note: 'Image resized for the web and converted to WebP. Manufacturer, package, or component values may differ.',
    imageKind: 'photograph',
  },
  'pot-10k': {
    src: '/products/pot-10k.webp',
    sourcePage:
      'https://www.sparkfun.com/rotary-potentiometer-10k-ohm-linear.html',
    attribution: 'SparkFun Electronics',
    match: 'representative',
    note: 'Image resized for the web and converted to WebP. Manufacturer, package, or component values may differ.',
    imageKind: 'photograph',
  },
  pushbutton: {
    src: '/products/pushbutton.webp',
    sourcePage: 'https://www.sparkfun.com/mini-pushbutton-switch.html',
    attribution: 'SparkFun Electronics',
    match: 'representative',
    note: 'Image resized for the web and converted to WebP. Manufacturer, package, or component values may differ.',
    imageKind: 'photograph',
  },
  'reed-switch': {
    src: '/products/reed-switch.webp',
    sourcePage: 'https://www.sparkfun.com/reed-switch.html',
    attribution: 'SparkFun Electronics',
    match: 'representative',
    note: 'Image resized for the web and converted to WebP. Manufacturer, package, or component values may differ.',
    imageKind: 'photograph',
  },
  ldr: {
    src: '/products/ldr.webp',
    sourcePage: 'https://www.sparkfun.com/mini-photocell.html',
    attribution: 'SparkFun Electronics',
    match: 'representative',
    note: 'Image resized for the web and converted to WebP. Manufacturer, package, or component values may differ.',
    imageKind: 'photograph',
  },
  fsr: {
    src: '/products/fsr.webp',
    sourcePage: 'https://www.sparkfun.com/force-sensitive-resistor-0-5.html',
    attribution: 'SparkFun Electronics',
    match: 'representative',
    note: 'Image resized for the web and converted to WebP. Manufacturer, package, or component values may differ.',
    imageKind: 'photograph',
  },
  'ntc-10k': {
    src: '/products/ntc-10k.webp',
    sourcePage: 'https://www.adafruit.com/product/372',
    attribution: 'Adafruit Industries',
    match: 'representative',
    note: 'Image resized for the web and converted to WebP. Manufacturer, package, or component values may differ.',
    imageKind: 'photograph',
  },
  'piezo-passive': {
    src: '/products/piezo-passive.webp',
    sourcePage: 'https://www.adafruit.com/product/160',
    attribution: 'Adafruit Industries',
    match: 'representative',
    note: 'Image resized for the web and converted to WebP. Manufacturer, package, or component values may differ.',
    imageKind: 'photograph',
  },
  tmp36: {
    src: '/products/tmp36.webp',
    sourcePage: 'https://www.adafruit.com/product/165',
    attribution: 'Adafruit Industries',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  lm35: {
    src: '/products/lm35.webp',
    sourcePage: 'https://www.robotsepeti.com/lm35-sicaklik-sensoru',
    attribution: 'Robot Sepeti',
    match: 'representative',
    note: 'Image resized for the web and converted to WebP. Manufacturer, package, or component values may differ.',
    imageKind: 'photograph',
  },
  dht22: {
    src: '/products/dht22.webp',
    sourcePage: 'https://www.adafruit.com/product/385',
    attribution: 'Adafruit Industries',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  ds18b20: {
    src: '/products/ds18b20.webp',
    sourcePage: 'https://www.adafruit.com/product/374',
    attribution: 'Adafruit Industries',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'bme280-bare': {
    src: '/products/bme280-bare.webp',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:BME280.jpg',
    attribution: 'Laserlicht / Wikimedia Commons — BME280.jpg',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP. Macro photograph of a BME280 chip on a PCB.',
    imageKind: 'photograph',
    licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    license: 'CC BY-SA 4.0',
  },
  'bme280-adafruit': {
    src: '/products/bme280-adafruit.webp',
    sourcePage: 'https://www.adafruit.com/product/2652',
    attribution: 'Adafruit Industries',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'bmp280-adafruit': {
    src: '/products/bmp280-adafruit.webp',
    sourcePage: 'https://www.adafruit.com/product/2651',
    attribution: 'Adafruit Industries',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'bh1750-adafruit': {
    src: '/products/bh1750-adafruit.webp',
    sourcePage: 'https://www.adafruit.com/product/4681',
    attribution: 'Adafruit Industries',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'mpu6050-adafruit': {
    src: '/products/mpu6050-adafruit.webp',
    sourcePage: 'https://www.adafruit.com/product/3886',
    attribution: 'Adafruit Industries',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'hcsr04-5v-sparkfun': {
    src: '/products/hcsr04-5v-sparkfun.webp',
    sourcePage:
      'https://www.sparkfun.com/ultrasonic-distance-sensor-hc-sr04.html',
    attribution: 'SparkFun Electronics',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'vl53l0x-adafruit': {
    src: '/products/vl53l0x-adafruit.webp',
    sourcePage: 'https://www.adafruit.com/product/3317',
    attribution: 'Adafruit Industries',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'ssd1306-adafruit-128x64': {
    src: '/products/ssd1306-adafruit-128x64.webp',
    sourcePage: 'https://www.adafruit.com/product/326',
    attribution: 'Adafruit Industries',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'lcd-backpack-adafruit': {
    src: '/products/lcd-backpack-adafruit.webp',
    sourcePage: 'https://www.adafruit.com/product/292',
    attribution: 'Adafruit Industries',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'ds3231-adafruit': {
    src: '/products/ds3231-adafruit.webp',
    sourcePage: 'https://www.adafruit.com/product/3013',
    attribution: 'Adafruit Industries',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'mcp4725-adafruit': {
    src: '/products/mcp4725-adafruit.webp',
    sourcePage: 'https://www.adafruit.com/product/935',
    attribution: 'Adafruit Industries',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'ads1115-adafruit': {
    src: '/products/ads1115-adafruit.webp',
    sourcePage: 'https://www.adafruit.com/product/1085',
    attribution: 'Adafruit Industries',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'pca9685-adafruit': {
    src: '/products/pca9685-adafruit.webp',
    sourcePage: 'https://www.adafruit.com/product/815',
    attribution: 'Adafruit Industries',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'neopixel-ws2812b': {
    src: '/products/neopixel-ws2812b.webp',
    sourcePage: 'https://www.pololu.com/product/2549',
    attribution: 'Pololu Corporation',
    match: 'representative',
    note: 'Image resized for the web and converted to WebP. Manufacturer, package, or component values may differ.',
    imageKind: 'photograph',
  },
  'tb6612fng-sparkfun': {
    src: '/products/tb6612fng-sparkfun.webp',
    sourcePage:
      'https://www.sparkfun.com/sparkfun-motor-driver-dual-tb6612fng-1a.html',
    attribution: 'SparkFun Electronics',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'drv8833-adafruit': {
    src: '/products/drv8833-adafruit.webp',
    sourcePage: 'https://www.adafruit.com/product/3297',
    attribution: 'Adafruit Industries',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'a4988-pololu': {
    src: '/products/a4988-pololu.webp',
    sourcePage: 'https://www.pololu.com/product/1182',
    attribution: 'Pololu Corporation',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'hobby-servo': {
    src: '/products/hobby-servo.webp',
    sourcePage: 'https://www.adafruit.com/product/169',
    attribution: 'Adafruit Industries',
    match: 'representative',
    note: 'Image resized for the web and converted to WebP. Manufacturer, package, or component values may differ.',
    imageKind: 'photograph',
  },
  'microsd-adafruit-254': {
    src: '/products/microsd-adafruit-254.webp',
    sourcePage: 'https://www.adafruit.com/product/254',
    attribution: 'Adafruit Industries',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'microsd-adafruit-4682': {
    src: '/products/microsd-adafruit-4682.webp',
    sourcePage: 'https://www.adafruit.com/product/4682',
    attribution: 'Adafruit Industries',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'sht31-adafruit': {
    src: '/products/sht31-adafruit.webp',
    sourcePage: 'https://www.adafruit.com/product/2857',
    attribution: 'Adafruit Industries',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'aht20-adafruit': {
    src: '/products/aht20-adafruit.webp',
    sourcePage: 'https://www.adafruit.com/product/4566',
    attribution: 'Adafruit Industries',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'ina219-adafruit': {
    src: '/products/ina219-adafruit.webp',
    sourcePage: 'https://www.adafruit.com/product/904',
    attribution: 'Adafruit Industries',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'tca9548a-adafruit': {
    src: '/products/tca9548a-adafruit.webp',
    sourcePage: 'https://www.adafruit.com/product/2717',
    attribution: 'Adafruit Industries',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'max9814-adafruit': {
    src: '/products/max9814-adafruit.webp',
    sourcePage: 'https://www.adafruit.com/product/1713',
    attribution: 'Adafruit Industries',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'pam8302-adafruit': {
    src: '/products/pam8302-adafruit.webp',
    sourcePage: 'https://www.adafruit.com/product/2130',
    attribution: 'Adafruit Industries',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  lm358: {
    src: '/products/lm358.webp',
    sourcePage:
      'https://learn.sparkfun.com/tutorials/beginner-parts-kit-identification-guide/all',
    attribution: 'SparkFun Electronics',
    match: 'representative',
    note: 'Image resized for the web and converted to WebP. Manufacturer, package, or component values may differ.',
    imageKind: 'photograph',
  },
  sn74hc595: {
    src: '/products/sn74hc595.webp',
    sourcePage: 'https://www.adafruit.com/product/450',
    attribution: 'Adafruit Industries',
    match: 'representative',
    note: 'Image resized for the web and converted to WebP. Manufacturer, package, or component values may differ.',
    imageKind: 'photograph',
  },
  'bss138-adafruit': {
    src: '/products/bss138-adafruit.webp',
    sourcePage: 'https://www.adafruit.com/product/757',
    attribution: 'Adafruit Industries',
    match: 'exact',
    note: 'Image resized for the web and converted to WebP.',
    imageKind: 'photograph',
  },
  'flex-sensor': {
    src: '/products/flex-sensor.webp',
    sourcePage: 'https://www.sparkfun.com/flex-sensor-2-2.html',
    attribution: 'SparkFun Electronics',
    match: 'representative',
    note: 'Image resized for the web and converted to WebP. Manufacturer, package, or component values may differ.',
    imageKind: 'photograph',
  },
};
